mailto: sensor-dream@sensor-dream.ru commiter: auto-commit

diff --git a/application/prepartion/nginx/404 b/application/prepartion/nginx/404
--- a/application/prepartion/nginx/404
+++ b/application/prepartion/nginx/404
@@ -1,12 +1,76 @@
 #!/bin/env bash
-cat <<EOF | sudo tee 404.html
+# -*- coding: utf-8 -*-
+#
+## @Author: sensor-dream
+## @Email: sensor-dream@sensor-dream.ru
+## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
+## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
+## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
+## @License: http://www.apache.org/licenses/LICENSE-2.0
+## @Site: https://sensor-dream.ru
+## @File: 404
+## @Creation date file: 13.09.2020, 11:33:55
+
+declare -rx s404_script_source="$BASH_SOURCE"
+
+temp_one="$(dirname ${s404_script_source})"
+if [[ "${temp_one}" == '.' ]]; then
+  declare -rx s404_script_source_path="$(pwd)"
+else
+  declare -rx s404_script_source_path="${temp_one}"
+fi
+
+if [[ -z "${main_run_script_path}" ]]; then
+  declare -rx main_run_script_path="$(pwd)"
+  printf "Script runs from path: %s\n" "${main_run_script_path}"
+fi
+
+if [[ -z "${main_cfg_script_source}" ]]; then
+  check=1
+  while [[ "${check}" -eq 1 ]]; do
+    if [[ ! -f 'main.cfg' ]]; then
+      if [[ "$(pwd)" != "/" ]]; then
+        cd ../
+      else
+        cd ${main_run_script_path}
+        check=0
+        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
+        tput sgr0
+        exit 1
+      fi
+    else
+      check=0
+      declare -rx main_project_path="$(pwd)"
+      . "${main_project_path}/main.cfg" "$@"
+      cd "${main_run_script_path}"
+    fi
+  done
+fi
+
+printf "Loading: %s\n" "$(readlink -m ${s404_script_source})"
+
+function main_s404_script_source() {
+
+  # prinf "Initialise main function of 404 script source\n";
+
+  cat <<EOF | sudo tee /usr/share/nginx/html/404.html
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
 <head>
+  <title>${cfg_org} - birth - 23.06.06 - teddy bear</title>
+  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
+  <style type="text/css">
+    /*<![CDATA[*/
+     /*]]>*/
+  </style>
+  </style>
 </head>
 <body>
-  <h1><strong>${cfg_full_org} (${cfg_org} - 23.06.06 - teddy bear) error!</strong></h1>
-  <h4 style="color: red;">The page you are looking for is not found.</h4>
+  Zero
 </body>
 </html>
 EOF
+
+}
+
+main_s404_script_source "$@"
diff --git a/application/prepartion/nginx/conf b/application/prepartion/nginx/conf
--- a/application/prepartion/nginx/conf
+++ b/application/prepartion/nginx/conf
@@ -1,6 +1,59 @@
 #!/bin/env bash
+# -*- coding: utf-8 -*-
+#
+## @Author: sensor-dream
+## @Email: sensor-dream@sensor-dream.ru
+## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
+## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
+## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
+## @License: http://www.apache.org/licenses/LICENSE-2.0
+## @Site: https://sensor-dream.ru
+## @File: conf
+## @Creation date file: 13.09.2020, 11:32:44
 
-cat <<EOF | sudo tee /etc/nginx/nginx.conf
+declare -rx conf_script_source="$BASH_SOURCE"
+
+temp_one="$(dirname ${conf_script_source})"
+if [[ "${temp_one}" == '.' ]]; then
+  declare -rx conf_script_source_path="$(pwd)"
+else
+  declare -rx conf_script_source_path="${temp_one}"
+fi
+
+if [[ -z "${main_run_script_path}" ]]; then
+  declare -rx main_run_script_path="$(pwd)"
+  printf "Script runs from path: %s\n" "${main_run_script_path}"
+fi
+
+if [[ -z "${main_cfg_script_source}" ]]; then
+  check=1
+  while [[ "${check}" -eq 1 ]]; do
+    if [[ ! -f 'main.cfg' ]]; then
+      if [[ "$(pwd)" != "/" ]]; then
+        cd ../
+      else
+        cd ${main_run_script_path}
+        check=0
+        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
+        tput sgr0
+        exit 1
+      fi
+    else
+      check=0
+      declare -rx main_project_path="$(pwd)"
+      . "${main_project_path}/main.cfg" "$@"
+      cd "${main_run_script_path}"
+    fi
+  done
+fi
+
+printf "Loading: %s\n" "$(readlink -m ${conf_script_source})"
+
+function main_conf_script_source() {
+
+  # prinf "Initialise main function of conf script source\n";
+
+  cat <<EOF | sudo tee /etc/nginx/nginx.conf
 # For more information on configuration, see:
 #   * Official English Documentation: http://nginx.org/en/docs/
 #   * Official Russian Documentation: http://nginx.org/ru/docs/
@@ -14,14 +67,18 @@ pid /run/nginx.pid;
 include /usr/share/nginx/modules/*.conf;
 
 events {
-    worker_connections 1024;
+    worker_connections 2048;
 }
 
 http {
 
-    more_set_headers 'Server: ${cfg_full_org} (${cfg_org} - 23.06.06 - teddy bear)';
+    more_set_headers 'Server: SDBS - 23.06.06 - best small bear badaboom';
 
-    subs_filter '<center>nginx/1.18.0</center>' '<center>${cfg_full_org} (${cfg_org} - 23.06.06 - teddy bear)</center>' gior;
+    subs_filter '<center>nginx/1.18.0</center>' '<center>SDBS - 23.06.06 -best small bear badaboom</center>' gior;
+
+    subs_filter 'Sensor-Dream Boxed System' '<span style="color: #f5bb09;">S</span>ensor-<span style="color: #3ea852;">D</span>ream <span style="color: #ea4334;">B</span>oxed <span style="color: #4285f4;">S</span>ystem' gior;
+
+    subs_filter 'Server: SDBS' 'Server: <strong><span style="color: #f5bb09;">S</span><span style="color: #3ea852;">D</span><span style="color: #ea4334;">B</span><span style="color: #4285f4;">S</span></strong>' gior;
 
     log_format  main  '\$remote_addr - \$remote_user [\$time_local] "\$request" '
                       '\$status \$body_bytes_sent "\$http_referer" '
@@ -91,3 +148,7 @@ http {
 
 }
 EOF
+
+}
+
+main_conf_script_source "$@"
diff --git a/application/prepartion/nginx/index b/application/prepartion/nginx/index
--- a/application/prepartion/nginx/index
+++ b/application/prepartion/nginx/index
@@ -1,18 +1,187 @@
 #!/bin/env bash
-cat <<EOF | sudo tee index.html
+# -*- coding: utf-8 -*-
+#
+## @Author: sensor-dream
+## @Email: sensor-dream@sensor-dream.ru
+## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
+## @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
+## @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
+## @License: http://www.apache.org/licenses/LICENSE-2.0
+## @Site: https://sensor-dream.ru
+## @File: index
+## @Creation date file: 13.09.2020, 11:31:11
+
+declare -rx index_script_source="$BASH_SOURCE"
+
+temp_one="$(dirname ${index_script_source})"
+if [[ "${temp_one}" == '.' ]]; then
+  declare -rx index_script_source_path="$(pwd)"
+else
+  declare -rx index_script_source_path="${temp_one}"
+fi
+
+if [[ -z "${main_run_script_path}" ]]; then
+  declare -rx main_run_script_path="$(pwd)"
+  printf "Script runs from path: %s\n" "${main_run_script_path}"
+fi
+
+if [[ -z "${main_cfg_script_source}" ]]; then
+  check=1
+  while [[ "${check}" -eq 1 ]]; do
+    if [[ ! -f 'main.cfg' ]]; then
+      if [[ "$(pwd)" != "/" ]]; then
+        cd ../
+      else
+        cd ${main_run_script_path}
+        check=0
+        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
+        tput sgr0
+        exit 1
+      fi
+    else
+      check=0
+      declare -rx main_project_path="$(pwd)"
+      . "${main_project_path}/main.cfg" "$@"
+      cd "${main_run_script_path}"
+    fi
+  done
+fi
+
+printf "Loading: %s\n" "$(readlink -m ${index_script_source})"
+
+function main_index_script_source() {
+
+  # prinf "Initialise main function of index script source\n";
+
+  cat <<EOF | sudo tee /usr/share/nginx/html/index.html
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="ru">
 <head>
-  <title>Webserver ${cfg_full_org} Test Page (${cfg_org} - <strong>23.06.06</strong> - teddy bear)</title>
+  <title>${cfg_org}</title>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   <style type="text/css">
     /*<![CDATA[*/
+      body {
+        padding: 0px;
+        margin: 0px;
+        border-width: 0px;
+        background-color: white;
+        font-size: 1.2em;
+      }
+
+      body, .app {
+        width: 100vw;
+        height: 100vh;
+      }
+
+      .app {
+
+        display: flex;
+	      display: -webkit-box;
+	      display: -webkit-flex;
+	      display: -ms-flexbox;
+
+      }
+
+      .app, .org, .footer {
+        flex-direction: column;
+	      -webkit-box-orient: vertical;
+	      -webkit-box-direction: normal;
+	      -webkit-flex-direction: column;
+	      -ms-flex-direction: column;
+
+        justify-content: center;
+	      -webkit-box-pack: justify;
+	      -webkit-justify-content: center;
+	      -ms-flex-pack: justify;
+
+        align-content: center;
+	      -webkit-align-content: center;
+	      -ms-flex-line-pack: distribute;
+
+        align-items: center
+	      -webkit-box-align: center;
+	      -webkit-align-items: center;
+	      -ms-flex-align: center;
+      }
+
+      .org {
+        padding: 10px;
+        /***
+          border-bottom: 1px solid rgba(0,0,0,0.1);
+          */
+        text-align: center;
+      }
+      .footer {
+        text-align: center;
+      }
+      .logo {
+        margin: 5px;
+        width: 64px;
+        height: 64px;
+      }
+      .mail-link {
+        margin-top: 40px;
+        width: 32px;
+        height: 32px;
+      }
+      a {
+        color: #4285F4;
+      }
+      .zero-page {
+        font-size: 1.4em;
+        font-weight: bold;
+      }
+      #license {
+        width: 50vw;
+        margin-top: 40px;
+        color: rgba(150,150,150,1);
+        font-size: 0.5em;
+        visibility: hidden;
+      }
     /*]]>*/
   </style>
 </head>
 <body>
-  <h1>Webserver <strong>${cfg_full_org}</strong> Test Page</h1>
-  <h3>(${cfg_org} - <strong>23.06.06</strong> - teddy bear)</h3>
+  <div class="app">
+    <img class="logo" src="favicon.ico"></img>
+    <div class="org">
+      <span class="zero-page">Zero page</span>
+      <h1>${cfg_full_org}</h1>
+    </div>
+    <div class="footer">
+      Server: ${cfg_org} - <strong>23.06.06</strong> - best small bear badaboom<br />
+      <a href="mailto: ${cfg_email}"><img class="mail-link" src="mail-link.png"></img></a>
+      <br />
+      <div id="license">
+        @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
+        <br />
+        @Copyright © sensor-dream. All rights reserved. Contacts: sensor-dream@sensor-dream.ru
+        <br />
+        @Copyright © Sensor-Dream Boxed System (SDBS). Contacts: sensor-dream@sensor-dream.ru
+        <br />
+        Licensed under the Apache License, Version 2.0 (the "License");
+        <br />
+        You may not use this file except in compliance with the License.
+        <br />
+        You may obtain a copy of the License at
+        <br />
+        http://www.apache.org/licenses/LICENSE-2.0
+        <br />
+        Unless required by applicable law or agreed to in writing, software
+        distributed under the License is distributed on an "AS IS" BASIS,
+        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+        See the License for the specific language governing permissions and
+        limitations under the License.
+      </div>
+      <br />
+      <!-- Double page: <a href="https://we-docs.sensor-dream.ru">sensor-dream.ru</a> -->
+    </div>
+  </div>
 </body>
 </html>
 EOF
+
+}
+
+main_index_script_source "$@"
