mailto: sensor-dream@sensor-dream.ru commiter: auto-commit

diff --git a/application/prepartion/nginx/index b/application/prepartion/nginx/index
--- a/application/prepartion/nginx/index
+++ b/application/prepartion/nginx/index
@@ -15,47 +15,47 @@ declare -rx index_script_source="$BASH_SOURCE"
 
 temp_one="$(dirname ${index_script_source})"
 if [[ "${temp_one}" == '.' ]]; then
-  declare -rx index_script_source_path="$(pwd)"
+    declare -rx index_script_source_path="$(pwd)"
 else
-  declare -rx index_script_source_path="${temp_one}"
+    declare -rx index_script_source_path="${temp_one}"
 fi
 
 if [[ -z "${main_run_script_path}" ]]; then
-  declare -rx main_run_script_path="$(pwd)"
-  printf "Script runs from path: %s\n" "${main_run_script_path}"
+    declare -rx main_run_script_path="$(pwd)"
+    printf "Script runs from path: %s\n" "${main_run_script_path}"
 fi
 
 if [[ -z "${main_cfg_script_source}" ]]; then
-  check=1
-  while [[ "${check}" -eq 1 ]]; do
-    if [[ ! -f 'main.cfg' ]]; then
-      if [[ "$(pwd)" != "/" ]]; then
-        cd ../
-      else
-        cd ${main_run_script_path}
-        check=0
-        echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
-        tput sgr0
-        exit 1
-      fi
-    else
-      check=0
-      declare -rx main_project_path="$(pwd)"
-      . "${main_project_path}/main.cfg" "$@"
-      cd "${main_run_script_path}"
-    fi
-  done
+    check=1
+    while [[ "${check}" -eq 1 ]]; do
+        if [[ ! -f 'main.cfg' ]]; then
+            if [[ "$(pwd)" != "/" ]]; then
+                cd ../
+            else
+                cd ${main_run_script_path}
+                check=0
+                echo -e '\e[31m'"!!! Not found configuration shared file !!!\033[0m"
+                tput sgr0
+                exit 1
+            fi
+        else
+            check=0
+            declare -rx main_project_path="$(pwd)"
+            . "${main_project_path}/main.cfg" "$@"
+            cd "${main_run_script_path}"
+        fi
+    done
 fi
 
 printf "Loading: %s\n" "$(readlink -m ${index_script_source})"
 
 function main_index_script_source() {
 
-  # prinf "Initialise main function of index script source\n";
-  [[ -z "${nginx_script_source_path}" ]] && local nginx_script_source_path='.'
-  [[ -z "$rev_timestamp" ]] && local rev_timestamp="$(cat ${nginx_script_source_path}/rev-timestamp.txt)"
+    # prinf "Initialise main function of index script source\n";
+    [[ -z "${nginx_script_source_path}" ]] && local nginx_script_source_path='.'
+    [[ -z "$rev_timestamp" ]] && local rev_timestamp="$(cat ${nginx_script_source_path}/rev-timestamp.txt)"
 
-  cat <<EOF | sudo tee /usr/share/nginx/html/index.html >/dev/null
+    cat <<EOF | sudo tee /usr/share/nginx/html/index.html >/dev/null
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="ru">
 <head>
@@ -186,6 +186,18 @@ function main_index_script_source() {
     </div>
   </div>
   <!-- <script src="https://ylei753tkpb.montastic.io/embed/script.js"></script> -->
+  <!-- Default Statcounter code for My domain sensor-dream.ru https://sensor-dream.ru -->
+    <script type="text/javascript">
+      var sc_project=12511240;
+      var sc_invisible=0;
+      var sc_security="6b0d0360";
+      var scJsHost = "https://";
+      document.write("<sc"+"ript type='text/javascript' src='" + scJsHost + "statcounter.com/counter/counter.js'></"+"script>");
+    </script>
+    <noscript>
+      <div class="statcounter"><a title="Web Analytics" href="https://statcounter.com/" target="_blank"><img class="statcounter" src="https://c.statcounter.com/12511240/0/6b0d0360/0/" alt="Web Analytics"></a></div>
+    </noscript>
+  <!-- End of Statcounter Code -->
 </body>
 </html>
 EOF
